name: Python Book

on: [push, pull_request]

jobs:
  tex:
    name: Checks and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Check Indentation
        run: make indent

      - name: Syntex Checks
        run: make checks

      - name: build PDFLaTeX
        run: make build

      - name: Analysis (git diff)
        if: failure()
        run: git diff

